from db.supabase_client import get_supabase
import json

class AssessmentRepository:

    @staticmethod
    def save_generated_question(
        question_id: str,
        subject_id: str,
        module_id: str,
        topic_id: str,
        difficulty: str,
        question_text: str,
        correct_answer: str = None,
        options: list = None
    ):
        supabase = get_supabase()
        
        # Determine Table
        table = "questions"
        
        # GUARDRAIL: Block Student Agent from polluting Teacher's Final Exam
        if module_id == "mod_final_exam" or module_id.endswith("_final_exam"):
             print(f"🛑 BLOCKED: Student Agent attempted write to '{module_id}'. This is a Teacher-Only zone.")
             return
             
        # Logic was: if module_id == "mod_final_exam": table = "questions_final"
        # Now we explicity REJECT that case.

        data = {
            "question_id": question_id,
            "subject_id": subject_id,
            "module_id": module_id,
            "topic_id": topic_id,
            "difficulty": difficulty,
            "question_text": question_text,
            "correct_answer": correct_answer,
            "options": json.dumps(options or [])
        }
        
        supabase.table(table).upsert(data).execute()
        
    @staticmethod
    def get_final_questions(subject_id: str, limit: int = None):
        """
        Fetch questions from questions_final table, sorted by difficulty (easy first).
        If limit is None, fetch ALL questions.
        """
        supabase = get_supabase()
        
        # Difficulty Sort Order: easy -> medium -> hard
        # We can't easily do custom sort in one query without a mapped column or conditional sort.
        # Simple approach: Fetch all for subject, then sort in Python.
        
        response = supabase.table("questions_final")\
            .select("*")\
            .eq("subject_id", subject_id)\
            .execute()
            
        questions = response.data
        if not questions:
            return []
            
        # Sort Logic
        diff_order = {"easy": 1, "medium": 2, "hard": 3}
        questions.sort(key=lambda q: diff_order.get(q.get("difficulty", "medium"), 2))
        
        if limit:
            return questions[:limit]
        return questions
        
    @staticmethod
    def create_assessment_attempt(
        attempt_id: str,
        student_id: str,
        module_id: str,
        score: float
    ):
        supabase = get_supabase()
        data = {
            "attempt_id": attempt_id,
            "student_id": student_id,
            "module_id": module_id,
            "score": score
            # attempted_at is auto-generated by DB default
        }
        supabase.table("student_attempts").insert(data).execute()

    @staticmethod
    def log_attempt_detail(
        attempt_id: str,
        question_id: str,
        student_answer: str,
        is_correct: bool,
    ):
        supabase = get_supabase()
        data = {
            "attempt_id": attempt_id,
            "question_id": question_id,
            "student_answer": student_answer,
            "is_correct": is_correct # Supabase handles bool
        }
        supabase.table("attempt_details").insert(data).execute()

    @staticmethod
    def get_student_attempt_details(student_id: str):
        supabase = get_supabase()
        
        # 1. Get Student Attempts
        attempts_res = supabase.table("student_attempts")\
            .select("attempt_id, attempted_at")\
            .eq("student_id", student_id)\
            .order("attempted_at", desc=True)\
            .execute()
            
        if not attempts_res.data:
            return []
            
        attempt_map = {a["attempt_id"]: a["attempted_at"] for a in attempts_res.data}
        attempt_ids = list(attempt_map.keys())
        
        # 2. Get Details
        details_res = supabase.table("attempt_details")\
            .select("*")\
            .in_("attempt_id", attempt_ids)\
            .execute()
            
        if not details_res.data:
            return []
            
        details = details_res.data
        question_ids = list(set(d["question_id"] for d in details if d["question_id"]))
        
        # 3. Get Questions (Check both tables)
        # We don't know which table a question is in easily without querying.
        # Query 'questions' first
        q_rows = []
        if question_ids:
            q1 = supabase.table("questions").select("question_id, question_text, difficulty, topic_id").in_("question_id", question_ids).execute()
            q_rows.extend(q1.data)
            
            # Find missing
            found_ids = {q["question_id"] for q in q1.data}
            missing = [qid for qid in question_ids if qid not in found_ids]
            
            if missing:
                q2 = supabase.table("questions_final").select("question_id, question_text, difficulty, topic_id").in_("question_id", missing).execute()
                q_rows.extend(q2.data)
        
        q_map = {q["question_id"]: q for q in q_rows}
        
        # 4. Merge
        results = []
        for d in details:
            qid = d["question_id"]
            q_data = q_map.get(qid, {})
            
            results.append({
                "question_id": qid,
                "is_correct": d["is_correct"],
                "question_text": q_data.get("question_text", "Unknown Question"),
                "difficulty": q_data.get("difficulty", "medium"),
                "topic_id": q_data.get("topic_id"),
                "attempted_at": attempt_map.get(d["attempt_id"])
            })
            
        # Sort by time
        results.sort(key=lambda x: x["attempted_at"] or "", reverse=True)
        return results
